#!/bin/bash

# Copyright 2025, dave horner
#
# HORNER conventions.
# undo_init.sh

# This script will remove the Git repository and any initialization files
# created by init_repo.sh. This operation is irreversible.

# Ask for confirmation before proceeding
echo "WARNING: This will remove the .git directory (erasing all Git history) and any files"
echo "generated solely by the init_repo.sh script (e.g. Cargo.toml, release-plz config, CHANGELOG.md)."
read -p "Are you sure you want to proceed? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Aborting undo operation."
    exit 0
fi

# Remove the Git repository directory if it exists.
if [ -d .git ]; then
    echo "Removing .git directory..."
    rm -rf .git
else
    echo "No .git directory found."
fi

# Remove Cargo.toml if it appears to be the minimal file created by init_repo.sh.
if [ -f Cargo.toml ]; then
    if grep -q 'version = "0.1.0"' Cargo.toml; then
        echo "Removing Cargo.toml..."
        rm -f Cargo.toml
    else
        echo "Cargo.toml exists and does not appear to be generated by init_repo.sh; leaving it intact."
    fi
fi

# Remove release-plz configuration file if it exists.
if [ -f release-plz.toml ]; then
    echo "Removing release-plz configuration file (release-plz.toml)..."
    rm -f release-plz.toml
fi

# Remove CHANGELOG.md if it exists (assuming it was generated by release-plz update).
if [ -f CHANGELOG.md ]; then
    echo "Removing CHANGELOG.md..."
    rm -f CHANGELOG.md
fi

echo "Undo complete. The repository is no longer initialized."
